In [1]:
%load_ext autoreload
%autoreload 2
%gui qt
%matplotlib qt5

import sys
import os

#import cupy as cp
import numpy as np
import matplotlib.pyplot as plt

### Load Metadata module

In [2]:
from oyLabImaging import Metadata

### Define path

In [3]:
fpath = '/bigstore/Microscopy Core/Jen/3T3_mRubyloss_HSV_20210818/'
MD = Metadata(fpath)

loaded ND2 metadata from /bigstore/Microscopy Core/Jen/3T3_mRubyloss_HSV_20210818/MRubyVirusDeath_08172021.nd2


# Check things out

In [5]:
MD.viewer()

# If needed, calculate drift correction

In [5]:
MD.CalculateDriftCorrection(Channel='DeepBlue', GPU=True)

opening file img_channel000_position002_time000000059_z000.tif
Loaded Pos2 group of images.

calculating drift correction for position Pos2
calculated drift correction for position Pos2
opening file img_channel000_position000_time000000059_z000.tif
Loaded Pos0 group of images.

calculating drift correction for position Pos0
calculated drift correction for position Pos0
opening file img_channel000_position001_time000000059_z000.tif
Loaded Pos1 group of images.

calculating drift correction for position Pos1
calculated drift correction for position Pos1


# Save metadata

In [ ]:
MD.save()

### See how the drift correction worked

In [12]:
MD.viewer()

opening index 8209
Loaded group 1 of images.


### you can export whatever is on your napari canvas to a video

In [ ]:
from oyLabImaging.Processing.imvisutils import export_napari_to_mp4
export_napari_to_mp4(filename='file name')

### If you want to segment cells, you can use a function called try_segmentation to see how the algorythm performs with different parameters. Any parameter value that's changed from the default should be added to the call for segmentation of the full data below. seg_widget.input_dict has that data as can be seen below

In [5]:
seg_widget = MD.try_segmentation()

# make empty results object

In [4]:
from oyLabImaging.Processing import results
R = results(MD=MD)


loaded results from pickle file


In [5]:
R()

Results object for path to experiment in path: 
 /bigstore/Microscopy Core/Jen/3T3_mRubyloss_HSV_20210818/

Available channels are : DIC N2, Widefield Green, Widefield Red, Widefield Dual Cyan, Widefield Blue.

Positions already segmented are : 0, 1, 2

Available positions : 0, 1, 2, 3, 4, 5.

Available frames : 92.


In [27]:
#doing this **b.input_dict will use the parameters you found earlier with segmentation.test_segmentation_params
R.segment_and_extract_features(MD=MD,Position=R.PosNames[0],NucChannel=R.channels[0],segment_type='cellpose_nuclei', threads=6, **seg_widget.input_dict)


Processing position 0


100%|███████████████████████████████████████████| 92/92 [01:11<00:00,  1.29it/s]



Finished loading and segmenting position 0
saved results


In [28]:
R.calculate_tracks(pos=R.PosNames[0], params=[(MD.channels[0],1),(MD.channels[2],1)], search_radius=30, maxStep=15)

Calculating tracks for position 0
linking frame 90
Finished connecting tracks

Finished finding splits


100%|█████████████████████████████████████████| 44/44 [00:00<00:00, 1733.80it/s]


saved results


In [6]:
R.show_points(R.PosNames[0], Channel=MD.channels[0])

/home/alo649/.conda/envs/oyimg_tt/lib/python3.8/site-packages/cupy/_environment.py:437: UserWarning: 
--------------------------------------------------------------------------------

  CuPy may not function correctly because multiple CuPy packages are installed
  in your environment:

    cupy-cuda111, cupy-cuda112

  Follow these steps to resolve this issue:

    1. For all packages listed above, run the following command to remove all
       existing CuPy installations:

         $ pip uninstall <package_name>

      If you previously installed CuPy via conda, also run the following:

         $ conda uninstall cupy

    2. Install the appropriate CuPy package.
       Refer to the Installation Guide for detailed instructions.

         https://docs.cupy.dev/en/stable/install.html

--------------------------------------------------------------------------------

  warnings.warn(f'''


<Points layer 'pointsmat' at 0x7fc6fefe3a60>

In [7]:
R.show_tracks(R.PosNames[0], J=np.arange(50))

<Tracks layer 'trackmat' at 0x7fc6f9b576a0>

## Open track explorer in napari and look at your data.

In [18]:
R.track_explorer()

Traceback (most recent call last):
  File "src/psygnal/_signal.py", line 990, in _run_emit_loop
  File "src/psygnal/_weak_callback.py", line 418, in cb
  File "/home/alo649/.conda/envs/oyimg_tt/lib/python3.8/site-packages/magicgui/widgets/_function_gui.py", line 256, in _on_change
    self()
  File "/home/alo649/.conda/envs/oyimg_tt/lib/python3.8/site-packages/magicgui/widgets/_function_gui.py", line 342, in __call__
    value = self._function(*bound.args, **bound.kwargs)
  File "/home/alo649/Repos/oyLabImaging/oyLabImaging/Processing/Results.py", line 550, in widget
    if PosLbl.numtracks:
  File "/home/alo649/Repos/oyLabImaging/oyLabImaging/Processing/PosLbl.py", line 321, in numtracks
    return self.trackinds.shape[0]
AttributeError: 'PosLbl' object has no attribute 'trackinds'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/psygnal/_signal.py", line 990, in _run_emit_loop
  File "src/psygnal/_weak_callback.py",

In [16]:
t0 = R.PosLbls[R.PosNames[0]].get_track(0)
MD.stkread(Pos = R.PosNames[0], ch=MD.channels[0])

{}

In [17]:
MD.viewer()

Viewer(axes=Axes(visible=False, labels=True, colored=True, dashed=False, arrows=True), camera=Camera(center=(0.0, 327.9569964721195, 460.0183080824921), zoom=0.5828725166369513, angles=(0.0, 0.0, 90.0), perspective=0.0, interactive=True), cursor=Cursor(position=(4.0, 119.95310655241416), scaled=True, size=1, style=<CursorStyle.STANDARD: 'standard'>), dims=Dims(ndim=2, ndisplay=2, last_used=0, range=((0.0, 2.0, 1.0), (0.0, 2.0, 1.0)), current_step=(0, 0), order=(0, 1), axis_labels=('1', '2')), grid=GridCanvas(stride=1, shape=(-1, -1), enabled=False), layers=[], scale_bar=ScaleBar(visible=False, colored=False, ticks=True, position=<Position.BOTTOM_RIGHT: 'bottom_right'>, font_size=10.0, unit='um'), text_overlay=TextOverlay(visible=False, color=array([0.5, 0.5, 0.5, 1. ]), font_size=10.0, position=<TextOverlayPosition.TOP_LEFT: 'top_left'>, text=''), overlays=Overlays(interaction_box=InteractionBox(points=None, show=False, show_handle=False, show_vertices=False, selection_box_drag=None, s

opening index 8190
Loaded group 0 of images.
opening index 8220
Loaded group 2 of images.


In [10]:
R.PosLbls[R.PosNames[0]].trackinds

array([array([15, 18, 19, 21, 14, 20, 20, 17, 15, 11, 11, 11, 10, 12, 13, 12, 13,
              12, 9, 11, 16, 13, 13, 11, 10, 14, 12, 16, 14, 15, 13, 14, 12, 12,
              11, 11, 12, 17, 13, 17, 17, 17, 15, 16, 15, 15, 16, 14, 14, 15, 15,
              12, 12, 15, 18, 14, 15, 14, 16, 13, 16, 14, 17, 16, 16, 16, 16, 14,
              15, 16, 13, 14, 14, 14, 16, 14, 16, 10, 16, 13, 15, 15, 15, 14, 17,
              13, 15, 13, 14, 13, 17, None], dtype=object)                       ,
       array([23, 35, 37, 37, 31, 31, 32, 26, 22, 18, 17, 18, 17, 21, 19, 17, 19,
              18, 15, 16, 22, 19, 20, 16, 18, 20, 19, 21, 19, 22, 19, 21, 20, 16,
              14, 18, 20, 22, 18, 21, 22, 23, 20, 21, 19, 20, 21, 18, 19, 21, 19,
              17, 18, 20, 23, 17, 19, 19, 22, 18, 19, 19, 22, 21, 22, 22, 20, 19,
              22, 20, 20, 18, 18, 19, 21, 20, 20, 16, 21, 19, 20, 21, 19, 19, 21,
              17, 19, 18, 20, 19, 21, None], dtype=object)                       ,
       array([3

## Ways to get data out, either to csv or as a matrix

In [ ]:
R.property_matrix?

In [ ]:
R.prop_to_csv?

In [35]:
t0 = R.tracks(0)

In [37]:
i=20
plt.plot(t0(i).T, t0(i).mean(MD.channels[4]))
plt.show()

### you can see a movie of a single tracked cell in different channels

In [ ]:
i=37
t0(i).show_movie(['DeepBlue','Red', 'Green'], cmaps=['cyan', 'magenta', 'yellow'])

### Routine for making a video with added plotting of fluorescence trajectories


In [ ]:

filename = 'your filename'
import matplotlib.animation as animation
dt=30
ims=[]
fig = plt.figure(facecolor='k')
ax1 = fig.add_subplot(2,1,1,facecolor='k')
ax2 = fig.add_subplot(2,1,2,facecolor='k')


ax2.spines['bottom'].set_color('w')
ax2.spines['top'].set_color('w')
ax2.spines['left'].set_color('w')
ax2.spines['right'].set_color('w')
ax2.tick_params(axis='x', colors='w')
ax2.tick_params(axis='y', colors='w')
for j in range(viewer.dims.range[0][1].astype(int)+1):
    viewer.dims.current_step=[j,0,0]
    ax1.set_position([0, 0, 0.5, 1])
    im = ax1.imshow(viewer.window.qt_viewer.canvas.render(),animated=True)
    t1 = ax1.text(10, 1, "%02d:%02d h"%(int(j*dt/60),j*dt%60),color='w')
    ax2.set_position([0.55, 0.3, 0.35, 0.4])
    # add as many trajectories as you want
    line1 = ax2.plot(t0(i).T[:j]/2, stats.zscore(t0(i).mean('DeepBlue'))[:j],'c',animated=True)
    line2 = ax2.plot(t0(i).T[:j]/2, stats.zscore(t0(i).mean('Red'))[:j],'m',animated=True)
    line3 = ax2.plot(t0(i).T[:j]/2, stats.zscore(t0(i).mean('Green'))[:j],'y',animated=True)
    line4 = ax2.plot(t0(i).T[:j]/2, stats.zscore(t0(i).area)[:j],'r',animated=True)
    ax2.legend(['Nuclei', 'mCherry', 'Death', 'Nuc. Area'], bbox_to_anchor=(0.7, 1.1), fancybox=True, facecolor='w', framealpha=1)
    ax2.set_xlabel('Time (h)', color='w')
    ax2.set_ylabel('AU', color='w')
    ims.append([t1, im, line1[0],line2[0],line3[0],line4[0],])
    

ani=animation.ArtistAnimation(fig,ims, interval=50,blit=True,repeat_delay=1000)

writer = animation.FFMpegWriter(fps=8, bitrate=1800)

ani.save(filename, writer=writer)

In [12]:
R.property_matrix(pos=R.PosNames[0],prop='centroid')

array([[[ 631.82542001,  352.3119065 ],
        [ 592.04821037,  356.18407597],
        [ 595.19411765,  351.90147059],
        ...,
        [ 594.10140148,  352.86150041],
        [ 593.79673469,  353.08326531],
        [          nan,           nan]],

       [[ 948.00663717, 1834.61017699],
        [ 943.45590231, 1831.07734057],
        [ 939.61171841, 1831.69348491],
        ...,
        [ 952.23636364, 1834.44409091],
        [ 952.07568294, 1835.37796686],
        [          nan,           nan]],

       [[1184.58064516, 1630.81226864],
        [1184.73197556, 1626.71038697],
        [1189.93284748, 1630.4903696 ],
        ...,
        [1185.07920792, 1630.23168317],
        [1185.66440678, 1631.11428571],
        [          nan,           nan]],

       ...,

       [[ 157.19968717, 1836.56308655],
        [ 164.8482371 , 1833.45068983],
        [ 184.1978022 , 1847.68131868],
        ...,
        [          nan,           nan],
        [          nan,           nan],
        [

In [20]:
R.PosLbls[R.PosNames[0]].framelabels[0].regionprops

,area,bbox,bbox_area,centroid,convex_area,eccentricity,equivalent_diameter,euler_number,extent,feret_diameter_max,...,mean_Widefield Dual Cyan,max_Widefield Dual Cyan,min_Widefield Dual Cyan,90th_Widefield Dual Cyan,median_Widefield Dual Cyan,mean_Widefield Blue,max_Widefield Blue,min_Widefield Blue,90th_Widefield Blue,median_Widefield Blue
0,720,"(3, 2022, 45, 2048)",1092,"(24.775, 2036.9875)",859,0.802399,30.277590,1,0.659341,44.271887,...,0.059537,0.068069,0.050491,0.061905,0.058083,0.150388,0.217194,0.085190,0.174463,0.132965
1,1738,"(65, 1819, 115, 1869)",2500,"(89.59321058688147, 1841.8204833141542)",1871,0.648446,47.041368,1,0.695200,56.400355,...,0.095053,0.132263,0.061356,0.111787,0.086815,0.238186,0.433975,0.097641,0.298515,0.193542
2,1443,"(118, 1878, 160, 1925)",1974,"(138.14760914760916, 1899.8274428274428)",1629,0.512040,42.863559,1,0.731003,52.697249,...,0.336933,0.933533,0.089325,0.478079,0.272995,0.275568,0.429901,0.090469,0.373035,0.232201
3,1918,"(136, 1810, 180, 1863)",2332,"(157.19968717413974, 1836.563086548488)",2017,0.555263,49.417340,1,0.822470,56.603887,...,0.090035,0.178070,0.055435,0.135309,0.071671,0.149183,0.441666,0.077469,0.241637,0.096245
4,765,"(174, 554, 207, 586)",1056,"(189.08235294117648, 570.2117647058824)",874,0.445905,31.209426,0,0.724432,36.674242,...,0.063079,0.069397,0.056259,0.065781,0.061745,0.086444,0.220642,0.077972,0.087563,0.082939
5,237,"(221, 507, 242, 524)",357,"(232.25316455696202, 514.620253164557)",269,0.704845,17.371176,1,0.663866,22.472205,...,0.061641,0.065689,0.056686,0.063617,0.060104,0.084752,0.090576,0.078812,0.086987,0.083374
6,1236,"(269, 192, 316, 227)",1645,"(293.77669902912623, 208.06553398058253)",1375,0.618384,39.670191,1,0.751368,49.040799,...,0.062710,0.071594,0.053619,0.067148,0.060486,0.157217,0.387146,0.076675,0.288065,0.091675
7,1941,"(274, 130, 322, 180)",2400,"(298.5919629057187, 154.2148377125193)",2022,0.318942,49.712754,1,0.808750,54.230987,...,0.094935,0.187866,0.055557,0.151094,0.075104,0.176402,0.591629,0.077942,0.318655,0.106827
8,2139,"(298, 1007, 351, 1075)",3604,"(325.8134642356241, 1042.5539971949509)",2554,0.754163,52.186774,1,0.593507,72.801099,...,0.121290,0.199753,0.061005,0.163153,0.079910,0.191224,0.504288,0.084885,0.262456,0.098305
9,1459,"(313, 1610, 360, 1666)",2632,"(335.46333104866346, 1640.9698423577793)",2008,0.718637,43.100539,1,0.554331,57.775427,...,0.061447,0.066757,0.055771,0.062988,0.059250,0.086142,0.096802,0.077835,0.088438,0.083038
